### ISSUE TITLE
Implement Anki's Button Translations

### ISSUE THREAD

**Issue by thatrobotdev** [C9HDN/anki-button-colours#4]
Hello! I'm not sure if this is feasible, but it would be nice to be able to use Anki's translations for the buttons, instead of English when the buttons are replaced with colored versions.

**Before (language Spanish):**
<img width="803" alt="Screenshot of anki buttons in spanish" src="https://user-images.githubusercontent.com/18013689/113537692-a1602d80-9596-11eb-97a0-fe6866d5c5e9.png">

**After:**
<img width="813" alt="Screenshot of colored anki buttons in english" src="https://user-images.githubusercontent.com/18013689/113537690-a0c79700-9596-11eb-83a8-a23ea1cf92ed.png">

**Comment by teaqu** [comment]
Hi thatrobotdev. This should definitely be possible. Let me take a look...

**Comment by teaqu** [comment]
Done :)

**Comment by thatrobotdev** [comment]
Thank you, you're amazing! 😄
