### ISSUE TITLE
Improvements: Unify functionality

### ISSUE THREAD

**Issue by cjdduarte** [C9HDN/anki-button-colours#6]
Could you add the features of this add-on to your add-on?

Large and Colorful Buttons
https://ankiweb.net/shared/info/1829090218

![image](https://user-images.githubusercontent.com/42243532/195307172-3364f8bd-6956-4ccb-8e3f-7a992c0e9ce6.png)

It broke in this new beta version of Anki 2.1.55 and it seems to have been abandoned.
https://forums.ankiweb.net/t/anki-2-1-55-beta/23470/52?u=cjdduarte

**Comment by teaqu** [comment]
Hey, I don't really want to add any additional features to this add-on as I like its simplicity. 
I noticed that the author has made some more recent changes to his other add-ons in 2022 so I think they might notice when 2.1.55 comes out of beta.
I'll make a note and see if I can made some fixes when I find the time however.
