### ISSUE TITLE
[FIXED] Unfortunately isn't working on my end (Anki ver 2.1.49)

### ISSUE THREAD

**Issue by andrettax** [C9HDN/anki-button-colours#7]
Hey, I really wanted this app to work on my Anki for PC (Windows 10)
For some reason it isn't working with default settings or if I try the code from other people from comments section on AnkiWeb or from YouTube videos. 
I tried disabling Beautify Anki to make sure it wasn't a conflict and enabling all the four buttons to show up.
I also tried on both in light and night mode.
Maybe configuration for 2.1 is different and I'm aware of this contribution: https://github.com/teaqu/anki-button-colours/pull/3
But I tried the exact same code on the image and it never changes anything
Have no idea what would be the reason... any ideas?
I'd highly appreciate advice! I have like other 10 Add-Ons working that have anything to do with the visuals of Anki but they are are running perfectly, what could be the reason?
Sorry for the trouble, thanks in advance.

**Comment by andrettax** [comment]
I fixed it, it was due to a sneaky option on another Add-On.
Sorry for the inconvenience!

**Comment by teaqu** [comment]
Sorry didn't see earlier glad you got it working!
